### ISSUE TITLE
fix ui periodical refresh

### ISSUE THREAD

**Issue by John-WL** [auto-webui-extensions-and-scripts/gimporter-extension#2]
The current implementation polls the images from the files every 3 seconds, which is pretty bad (it works though!). 

Instead of doing that, gimp and the webui should communicate through a socket connection. 
With this implementation, it would be possible to update the UI asynchronously when sending images from gimp.

**Comment by ljleb** [comment]
I see 2 issues described:
1. we should not use the filesystem to communicate between gimp and the webui
2. we have to find a way to only refresh ui images when we receive something from gimp

I'll propose a fix for the periodical refresh issue in the ui. I have scraped the gradio docs probably 3 to 4 times but I couldn't find a way to call js functions from python or trigger custom events programatically. It's not the ideal but it seems websockets could do the trick here.

**Comment by John-WL** [comment]
sure, I'll work on changing the filesystem implementation

**Comment by ljleb** [comment]
pr open, please have a look. As I said earlier, in my opinion using websockets as proposed in #3 is overkill. Ideally we should be able to just dispatch an event for it to update. I tried looking at the webui gradio-generated html and js but I'm not sure what event should be sent to which html element.

If anyone knows how to trigger gradio events programatically from python, which is what we're trying to do here, then please let us know.

**Comment by John-WL** [comment]
I think we can merge for now, and implement a better solution later if we find how to cleanly do this.

**Comment by ljleb** [comment]
related discussion on the subject: https://github.com/gradio-app/gradio/discussions/2752
